spring:
  application:
    name: service-discovery

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

