version: "3.9"
services:
  service-discovery:
    build: ./service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - service-discovery
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - service-discovery
      - product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - service-discovery
      - product-service
      - order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

