server:
  port: 8700

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/produtos/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/pedidos/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Simple fixed token for demo (gateway checks it)
security:
  token: SECRET-TOKEN-123

management:
  endpoints:
    web:
      exposure:
        include: health,info
